### PR TITLE
color contrast

### PR DESCRIPTION
**Pull request by brianteeman**
tweaks a few base colors to satisfy color-contrast a11y checks

impacted areas are 

- info box 
-- links
-- code

- footer
-- links
-- background

### CODE REVIEW

**Comment by nikosdion** [comment]
I agree with the reasoning, I disagree with the implementation, and I have an alternative which I believe would work (please test it with your tools as well).

You are changing the primary (branding) colour to change the links. That's the wrong way to go about it. You can define `$link-color` and `$link-color-dark` instead.

Same thing with changing `$pink`. In fact, I hate that Bootstrap uses the same shade for code in light and dark mode. It's best setting `$code-color` and `$code-color-dark` separately.

Changing the `$info` colour is actually a bad idea. It messes up the color of info button text (because Bootstrap uses WCAG's flawed colour contrast model to decide whether to use light or dark grey as the foreground button colour) and screws up the colour contrast under both WCAG 2 and APCA colour contrast models in dark mode. Same thing with the `$dark` colour. The problems can be fixed by adjusting the link colours, as per above.

Talking about bad colour models, I am not pulling this out of my ass. Please read https://blog.datawrapper.de/color-contrast-check-data-vis-wcag-apca/ for a great explainer with examples of how the WCAG 2 colour contrast model actually leads to inaccessible colour combinations. As I implied above, the fact that Bootstrap uses the WCAG 2 colour model to decide the button foreground is what led me to tweak the colours to what they currently are, ever so slightly different than the actual branding palette.

I believe that the best results under _both_ WCAG 2 _and_ APCA colour contrast models can be had by keeping the "Akeeba colours" section as-is and adding the following below it:

```scss
// Accessibility tweaks
$link-color: #116969;
$link-color-dark: #7dcaca;

$code-color: #b12a6e;
$code-color-dark: #c22774;
```

Try that in both light and dark mode and you'll see that the problem areas you identified now have excellent colour contrast. The WCAG 2 colour contrast model gives a stupidly great contrast which is largely phoney. Try the APCA colour contrast model and you'll see that in two out of three identified areas we are just good compromises. The best way to see what I am talking about is to check the contrast of regular info alert text against its background in dark mode with both WCAG 2 and APCA.

**Comment by brianteeman** [comment]
There are many ways to skin a cat. I went for what for me was the simplest. I am happy with any resolution.

PS I am well aware of the flaws in the contrast model. Sadly until all the tooling is updated we are stuick with using it. Rightly or wrongly most accessibility testers just use tools and accept what they say,

**Comment by brianteeman** [comment]
Your changes work in most places. Not your fault I forgot to list some of them

image

image

**Comment by brianteeman** [comment]
(and i forgot to test dark mode)

**Pull request closed without merging**
