### PR TITLE
Core-updates

### PR DESCRIPTION
**Pull request by brianteeman**
Summary
changed checkall to td
added scope=col to head
added scope=row to site - changed to th and set the font weight back to normal for url

### CODE REVIEW

**Comment by nikosdion** [comment]
Regarding the scope, my understanding reading [the documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th#scope) is that the browser will automatically determine that it's a column scope since it's a table head element, on the sole table row of the table's head. Isn't this change ultimately unnecessary?

Regarding the check-all column, would it not need a heading? I am not talking about sighted users. As a sighted user I can, well, _see_ what this column is supposed to do.

**Comment by brianteeman** [comment]
1. Technicaly that is perfectly correct. I see it like the trailing php array comma as a best practice for future proof and consistency.
2. Check-all is awkward. We have the same problem in Joomla and didnt have a perfect solution. The check-all is a cell in its own right it is not a heading for the individual checks in the cells below. What you really want is to have a th as a header to the cells below AND a check-all as a seperate item. Drupal 7 did this with a checkall outside of the table - sometimes placed visually with css in the th. https://www.drupal.org/project/drupal/issues/851164

**Comment by nikosdion** [comment]
Hm, the check-all header could MAYBE be handled with a bit of underhanded trickery, like putting a second TR in the THEAD but have it be `.visually-hidden`, the first cell be a TH and the rest a TR with the right `colspan` and `.d-none` to prevent it from being announced. Of course that's idle speculation. I have not tried that. Care to give it a go, if you have the time?

**Comment by brianteeman** [comment]
happy to look into that in the future. would like to finish what I have started first.

**Pull request merged**
