### PR TITLE
Update fr-FR.ini

### PR DESCRIPTION
**Pull request by AlainRnet**
forgotten keys and I don't understand ANOPTICON_REPORTS_LBL_TABLE_CAPTION="Table of action report entries
What is the context please?

### CODE REVIEW

**Comment by nikosdion** [comment]
This is part of the Site Reports page. This is the caption of the table displayed on that page, only made available to screen readers (for blind people to hear and have some context as to what that table is about).

**Comment by AlainRnet** [comment]
Thank you. I think something like "Tableau des entrées des rapports", I'll add it soon

Another thing: on page index.php?view=updatesummarytasks, there is only the language key PANOPTICON_UPDATESUMMARYTASKS_TITLE_NEW

**Comment by nikosdion** [comment]
Added to the POT file

**Comment by AlainRnet** [comment]
Okay, thank you. Is it better to work on the POT or INI file?

**Comment by nikosdion** [comment]
Always translate the .po file. The .ini files are generated from the .po files.

**Pull request merged**
