### PR TITLE
Update de-DE.po (Happy Easter Version)

### PR DESCRIPTION
**Pull request by NetSecond**
Not yet finished but much more translations.

### CODE REVIEW

**Comment by NetSecond** [comment]
Short Information:
In my texts/translations I try to leave out "you" ("Du"/"Sie"), i.e. to avoid polite phrases.

Furthermore, the software author included many more new language strings, which were inserted here as new/empty.
I will of course take these into account in the next update.

Therefore, please do not be surprised if empty strings suddenly appear as new in green and texts that have already been translated may have changed slightly because formal salutations are missing.

As always in IT:
Keep it short and informal...

;-) :-D

**Comment by nikosdion** [comment]
Please do not go out of your way to avoid the usage of personal pronouns. Computer messages are always meant to be deferential to the user. Use the polite form in your language. In German this is "Sie", in French it's "vous", in Greek the pronoun is implied based on the declension which is second plural person (i.e. the equivalent of "Sie" in German).

Given this guidance, would you need to re-evaluate your translation so far?

**Comment by NetSecond** [comment]
In the German language, a distinction is made between "Du" and "Sie" for the sake of respect, but in the computer world either "Du" has prevailed or personal addresses have been dispensed with entirely.

I see the third person without direct address as a good compromise before I "move back" one of the two sides ("Du" or "Sie") and a second language for "Du" only does double the work given the mass of text.

If simplified use without personal contact is not desired, I ask that my previous translation(s) be removed.
For my part, I can live with the English version and will probably finish the German one for myself.

A change back to "Sie" would be possible, but someone else should do it, as not only would the personal pronouns have to be reinserted again, but the grammar would also have to be adjusted.

By the way:
If a software doesn't address me directly as "Du" or "Sie", I have no problem with that, while personal pronouns sometimes even seem strange.

And:
Indirect communication is much easier to translate into other languages.

But:
It's your software and you should of course use/publish what you like.
I assumed that a neutral approach would do justice to everyone.

**Comment by NetSecond** [comment]
I found a lot of mixes of "Du" and "Sie" in older translations.
I try to find and fix them all.

**Comment by NetSecond** [comment]
New version coming soon ....

**Pull request closed without merging**
