### PR TITLE
Conection Doctor Site Icon

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the Site icon to the Connection Doctor page for consistency

Adds the Site icon AND restyle the Title to the updatesummarytasks for consistency

Adds the Site icon AND restyle the Title to the Actionsummarytasks for consistency

Adds the Site icon AND restyle the Title to the backuptasks for consistency

Adds the Site icon AND restyle the Title to the overrides for consistency

Adds the Site icon AND restyle the Title to the scannertasks for consistency

PS I have yet been unable to get the favicon for any site I just have the globe

image

image

### CODE REVIEW

**Comment by brianteeman** [comment]
a few more than I thought but should all be done now with icon and consistent styling for the site title

**Comment by nikosdion** [comment]
I like it :)

I will check into the favicon caching. Something is off, you are right.

BTW, GitHub complains about your commits not being signed with GPG. You can very easily tell Git to automatically sign your commits with your GPG key, see: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits I had made a JaB presentation in 2017, if memory serves, about why this matters. Basically, it ensures that nobody can slip a malicious commit into the Git chain undetected, as doing so would break the GPG signatures. It's the paranoid approach, but seeing things like CRA coming to life I believe that paranoia will essentially be legally mandated. Let's be paranoid. It costs us nothing.

**Comment by brianteeman** [comment]
Thanks for merging

They should have been signed. Must have unset the option when I updated smartgit

**Comment by nikosdion** [comment]
I don't blame you for getting confused. There are two things with "sign" in their name.

“Signing off” a commit, which is required for DCA, is adding the text "Signed-Off-By: " followed by a name and email address. This is just the committer saying that they take legal responsibility for abiding by the license of the repository. It's not a security feature. It's a legal pinkie-swear.

“Signing” a commit refers to a cryptographic operation performed by GnuPG (GPG). It takes the entire commit message and calculates a cryptographic signature against it using your private GPG key. The [reasoning is explained here](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html), [and elsewhere](https://andreas-augustin.dev/blogs/git/git_sign_commits/), [and this especially](https://betterprogramming.pub/why-and-how-you-should-sign-all-your-git-commits-94435516edae).

I feel that us FOSS developers should keep the security banner high and be the first to follow the best practices we evangelise. That's the only way that recalcitrant bureaucrats in Brussels and Washington, DC will believe us when we say that _our_ software is far more secure than the black box of proprietary software, giving us more leeway compared to proprietary vendors in laws like CRA. Besides, we should practice what we preach. After all, isn't that one of the reasons we put all of our work, including all its gnarly under the hood bits, in public scrutiny?

**Pull request merged**
