### PR TITLE
scss fix

### PR DESCRIPTION
**Pull request by brianteeman**
generate the css files correctly

before 
Code updated but still has issues :(

composer run-script scss 

```
> \Akeeba\Panopticon\Composer\InstallationScript::sass
'sass' is not recognized as an internal or external command,
operable program or batch file.
```

composer install
```
> \Akeeba\Panopticon\Composer\InstallationScript::copyNodeDependencies
> \Akeeba\Panopticon\Composer\InstallationScript::babel
> \Akeeba\Panopticon\Composer\InstallationScript::sass
'sass' is not recognized as an internal or external command,
operable program or batch file.
> \Akeeba\Panopticon\Composer\InstallationScript::copyPackageLock
> \Akeeba\Panopticon\Composer\InstallationScript::makeVersionPhp
> \Akeeba\Panopticon\Composer\InstallationScript::postComposerUpdate
> \Akeeba\Panopticon\Composer\InstallationScript::schemaUpdate
```

### CODE REVIEW

**Comment by brianteeman** [comment]
this isnt correct. it gets rid of the error but doesnt generate the css

**Comment by nikosdion** [comment]
Have you installed the [Saas](https://sass-lang.com/) compiler and made it available in your path?

**Comment by nikosdion** [comment]
Changing the key from `sass` to `scss` actually breaks this feature completely, since `\Akeeba\Panopticon\Composer\InstallationScript::sass` expect the key to be `sass`, see line 215.

The problem you have, and which is reported by PHP, is that you don't have the `sass` executable in your path.

I'll go ahead and close this PR as it's actually not valid.

**Comment by brianteeman** [comment]
no i had not installed it as I expected it to be in the packages.json as a devDependency

But even when I do install it (locally or globally) I'm still not getting any css generated

**Comment by brianteeman** [comment]
grrh windows

**Comment by nikosdion** [comment]
Sass is written in Dart. The canonical version is the one that's compiled into a binary from the Dart sources.

Dart can also be transpiled into JavaScript which is what they do for the JS version of Sass. However, it's both slower and not 100% identical to the compiled Dart version. I've had problems with it compiling Bootstrap in the past which is why I am not using it.

If the `sass` executable is available in your path, the `composer run-script scss` command does work. I've tested it on Linux and macOS. I no longer have a working dev environment on Windows anymore. I suspect it has to do with the fact that when you add something to the path it does not update open terminals and there is nothing similar to the `source ~/.profile` we do on _Real Operating Systems_ (😜) to reinitialise the environment.

**Comment by brianteeman** [comment]
in windows it needs to have ./node_modules/.bin in the path as that is where the sass command lives

**Comment by nikosdion** [comment]
That's the local copy of the Sass JS. If this borks try installing Sass with Chocolatey as instructed in https://sass-lang.com/install/ 

```
choco install sass
```

**Comment by brianteeman** [comment]
dont know why I didnt do choco first.

**Pull request closed without merging**
