### PR TITLE
min-height

### LINKED ISSUE #107: vh-100
`<div class="vh-100"></div>`

Not sure what the intention was for adding this line at the end of these files but it doesnt seem to be correct

> ViewTemplates\Selfupdate\default_noupdate.blade.php
> ViewTemplates\Users\form.blade.php

### PR DESCRIPTION
**Pull request by brianteeman**
closes #107 

> Otherwise the footer ended up midway through the window height even on a 14” laptop. I want it stuck to the bottom of the window.

works on all pages

### CODE REVIEW

**Comment by brianteeman** [comment]
Simplest option of three possibilities

**Comment by nikosdion** [comment]
The login page is no longer vertically centred. This needs to be addressed before I can merge.

**Comment by brianteeman** [comment]
ok I will check that

**Comment by nikosdion** [comment]
I'm going to adapt what you are doing a little bit, so I'm closing this PR. Most of it was good, except the changes to the login page. The trick there is to change the template's index.php to not put the minimum height when the user is logged out ;) You'll see.

**Comment by brianteeman** [comment]
I was just about to commit that

**Comment by brianteeman** [comment]
This works as you intended it to work - I had originally "fixed" a file that shouldnt have been fixed

**Comment by nikosdion** [comment]
The overall idea was good, I told you so :)

I did a few more changes. The login page needed a small `calc` usage to avoid Y scrollbars from showing.

I will also start working a little bit on the responsiveness of the login form on small screen heights (e.g. the Samsung A21 I use for testing on landscape mode).

**Pull request closed without merging**
