### PR TITLE
Style mime types

### PR DESCRIPTION
**Pull request by brianteeman**
It not necessary to include the mimetypes

### CODE REVIEW

**Comment by nikosdion** [comment]
Scripts do need the MIME type as they will not necessarily be `text/javascript`. They can also be [`importmap`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap), and [`module`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#applying_the_module_to_your_html) at the very least. It is also conceivable to use other MIME types for inline scripts, e.g. `application/json` [which results in the browser not parsing it, but allowing client-side code to access it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type). Therefore, the script part of the PR is definitely wrong, both conceptually, and because it does not conform to the title of the PR.

Regarding stylesheets, yes, you can omit the MIME type since only `text/css` is allowed, therefore it makes no sense outputting the type. I agree with this part of the PR.

Remove the changes from lines 69 and 72 and I can accept the PR.

**Comment by brianteeman** [comment]
The default value for a script is text/javascript hence it is not needed and the w3c validator will flag this.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type

**Comment by brianteeman** [comment]
ah - whoops. 

Did you mean that in the use case here in panopticon they could be json. 

In which case we will have to live with the validaotr warnings

**Comment by nikosdion** [comment]
> Did you mean that in the use case here in panopticon they could be json.

That, or importmap, or module.

So far, we have a specific script tag with MIME type `application/json` to hold the script options passed from the server- to the client-side, exactly like Joomla does. In the future, I might have to pass the initial data for Vue view in a _different_ script tag, again with the `application/json` MIME type.

Since we're moving from plain old JavaScript to ECMAScript modules, an `importmap` may become necessary. It serves a similar role to the class automap on the PHP side: it tells the browser where to find each module.

Likewise, ESM (ECMAScript Modules) need to be loaded with `type="module"` for the browser to know this is not plain old JavaScript, it's gotta to do something special.

Right now, out of these three features, I only use the latter. I hope that clarifies what I had in mind :)

**Pull request merged**
