### PR TITLE
Revert "Auxiliary commit to revert individual files from 8e48e29ad0ef…

### PR DESCRIPTION
**Pull request by brianteeman**
…ff1462a1c629d7175a120353fc49"

This reverts commit 39276e0d4a9a8160b94a033499781ebc15e23ab9, reversing changes made to 1eb95351bec659ad9b25446ef017da28bbfff2fb.

### CODE REVIEW

**Comment by brianteeman** [comment]
sorry abiout that

**Comment by nikosdion** [comment]
Don't beat yourself over it, it happens to all of us. As you know, I treat mistakes as teachable moments. Let's learn, or remember, something on the occasion of making a simple mistake that caused no harm.

You definitely know about the `.gitignore` file which tells Git which files to _not_ commit. The problem is that the `.gitignore` file itself is committed, so it's really not ideal when you have “personal” files in your working copy you want to exclude from commit, but don't want to pollute the `.gitignore` file with their names.

If only there was some kind of “personal” `.gitignore` file. Well, as it turns out, there is!

Enter `.git/info/exclude`. This is a file which applies only to your own working copy. It works exactly the same as `.gitignore`, meaning it has the same syntax. Since it's in the `.git` folder it does not get committed. It lives only on your computer.

**Comment by brianteeman** [comment]
ooh thats a new one on me. thanks for that although I have to say in thousands of pull requests I think this was the first time it happened

**Comment by nikosdion** [comment]
You're welcome!

**Pull request merged**
